baseurl = "https://zen-kalam-4ce959.netlify.com"
title = "シモキタコイン"

theme = "hugo-coder-master"

languagecode = "ja"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "シモキタコイン"
    description = "株式会社シモキタコイン"
    keywords = ""
    info = ""

# [[params.social]]
#     name = "Github"
#     weight = 1
#     url = "https://github.com/johndoe/"
# [[params.social]]
#     name = "Twitter"
#     weight = 2
#     url = "https://twitter.com/johndoe/"
# [[params.social]]
#     name = "LinkedIn"
#     weight = 3
#     url = "https://www.linkedin.com/in/johndoe/"

# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"
